{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div class="maincontentheader">
	<h1>{'Coupon validation'|i18n( 'design/standard/workflow' )}</h1>
</div>
<p>Coupon is not applicable because you are buying only sale items</p>
<form method="post" action={'shop/confirmorder'|ezurl( 'no' )}>
	<div class="buttonblock">
		<input class="button" type="submit" name="{$base}_CancelButton_{$event.id}"  value="{'Continue'|i18n( 'design/standard/workflow' )}" />
	</div>
</form>